In [37]:
import pandas as pd
import numpy as np

weather = pd.read_csv('./weather.csv')
trip = pd.read_csv('./trip.csv',error_bad_lines=False)
station = pd.read_csv('./station.csv')

b'Skipping line 50794: expected 12 fields, saw 20\n'

# 1- What is the average trip duration for a borrowed bicycle?

In [31]:
trip['tripduration'].mean()

1178.2956753399776

# 2- What's the most common age of a bicycle-sharer?

In [32]:
(2021 - trip['birthyear']).mode()[0].astype('int32')

34

# 3- Given all the weather data here, find the average precipitation per month, and the median precipitation?

In [137]:
def get_month(date_string):
    dt = datetime.strptime(date_string, '%m/%d/%Y')
    
    """
    turn date as string to a month e.g. 
    1/15/2001 = 1
    3/21/1975 = 3
    """
    return dt.month
weather['Month'] = weather['Date'].apply(get_month)
weather_test=weather.groupby('Month')['Precipitation_In'].mean()
weather_test

Month
1     0.143548
2     0.168421
3     0.156935
4     0.051333
5     0.012419
6     0.030500
7     0.012097
8     0.018226
9     0.041000
10    0.189000
11    0.187833
12    0.236290
Name: Precipitation_In, dtype: float64

# 4- What's the average number of bikes at a given bike station?

In [85]:
# station[station['decommission_date'].notnull()].mean()
station['current_dockcount'].mean()
#station[station['modification_date'].notnull()]['install_dockcount'].mean()

16.517241379310345

# 5- When a bike station is modified, is it more likely that it'll lose bikes or gain bikes? How do you know?

In [97]:
data=station[station['modification_date'].notnull()]
data[data['install_dockcount']!=data['current_dockcount']]

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN

# 6- Get all staitons that have more than or equale 20 bikes?

In [152]:
six_qustion=station[station['current_dockcount']> 20]
six_qustion

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
52,WF-01,Pier 69 / Alaskan Way & Clay St,47.614315,-122.354093,10/13/2014,18,NaN,24,NaN

# 7- Get all staitons that have zero bikes?

In [153]:
seven_qustion=station[station['current_dockcount']== 0]
seven_qustion

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015

# 8- Get all staitons that hse been modifiy it?

In [154]:
eight_qustion=station[station['modification_date'].notnull()]
eight_qustion

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN

In [158]:

def test():

    def assert_equal(actual,expected):
        assert actual == expected, f"Expected {expected} but got {actual}"

    assert_equal(trip['tripduration'].mean(), 1178.2956753399776)
    assert_equal((2021 - trip['birthyear']).mode()[0].astype('int32'), 34)
    assert_equal(weather_test.iloc[0], 0.14354838709677417)
    assert_equal(station['current_dockcount'].mean(), 16.517241379310345)
    assert_equal(data.iloc[0]['name'], '2nd Ave & Spring St')
    assert_equal(six_qustion.iloc[1]['install_date'], '10/13/2014')
    assert_equal(seven_qustion.iloc[2]['install_dockcount'], 20)
    assert_equal(eight_qustion.iloc[10]['current_dockcount'], 0)
    print("Success!!!")

test()

Success!!!